# Basic
title: 阿牛写字的地方
subtitle: 价值观民粹，用词刻薄
welcome_message: <a>每一个滥用文字排列技巧的背后，都掩盖着自己贫瘠的视角</a>

permalink: /:year/:month/:title/
highlighter: rouge
cover_color: slate
blog_button:
    title: 文章
    description: Visit blog
nav:
    - {title: 读书笔记, description: 最近的读书, url: 'http://neo123.me'}
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

