title:
subtitle:
welcome_message:
permalink: /:year/:month/:title/
highlighter: rouge
cover_color: slate
blog_button:
    title: 文章
    description: Visit blog
nav:
    - {title: 读书笔记, description: 最近的读书, url: 'http://neo123.me'}
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

